enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

patches-version = "v2.225.0-dev.13"
integrations-version = "v0.152.0-dev.8"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced Afn Red Icon"
build-mode = "both"
included-patches = "'Custom branding icon YouTube' 'MaterialYou'"
excluded-patches = "'Theme'"
version = "auto"

[YouTube Music]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced Afn Red Icon"
build-mode = "both"
included-patches = "'Custom branding icon YouTube Music'"
excluded-patches = "'Amoled'"
version = "auto"
