enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

patches-version = "v4.8.0-dev.4"
integrations-version = "v1.9.0-dev.3"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "both"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"

[YouTube Music]
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "both"
excluded-patches = "'Amoled'"
